/* oxlint-disable no-console */
import { parseSync } from "npm:oxc-parser";

async function getFileExports(path: string): Promise<string[]> {
  try {
    const content = await Deno.readTextFile(path);

    const { module, errors } = parseSync(path, content);

    if (errors && errors.length > 0) {
      console.warn(`[warning] Parsed ${path} with issues:`, errors);
    }

    if (!module?.staticExports) {
      return [];
    }

    const exportedNames = new Set<string>();

    for (const staticExport of module.staticExports) {
      for (const entry of staticExport.entries) {
        if (entry.isType) {
          continue;
        }

        const { kind } = entry.exportName;
        if (kind === "Name" && entry.exportName.name) {
          exportedNames.add(entry.exportName.name);
        }
      }
    }

    return Array.from(exportedNames);
  } catch (err) {
    console.error(`Failed to read or parse file at ${path}:`, err);
    return [];
  }
}

const HEADER = `// Automatically generated by "CODEGEN.ts". Do not edit manually.\n\n`;

function toSafeIdentifier(filename: string): string {
  let identifier = filename.replace(/[^a-zA-Z0-9]/g, "_");
  if (/^[0-9]/.test(identifier)) {
    identifier = "_" + identifier;
  }
  return identifier;
}

async function generateBarrelContent(filenames: string[]): Promise<string> {
  const contentParts = await Promise.all(
    filenames.map(async (file) => {
      const toImport = `./${file}`;
      const importAs = toSafeIdentifier(file);
      const exports = await getFileExports(file);

      if (exports.length === 0) {
        return "";
      }

      const importType = `import type * as ${importAs} from "${toImport}";\n`;

      const exportLets = exports
        .map((exp) => `export let ${exp}: typeof ${importAs}.${exp};\n`)
        .join("");

      const initializer =
        `import("${toImport}").then(m => {\n` +
        exports.map((exp) => `	${exp} = m.${exp};\n`).join("") +
        `});\n`;

      return importType + exportLets + initializer;
    })
  );

  return HEADER + contentParts.filter(Boolean).join("\n");
}

async function main() {
  const nameToFilenames: Record<string, string[]> = {};

  try {
    for await (const sibling of Deno.readDir(".")) {
      if (!sibling.isFile) {
        continue;
      }

      const { name: filename } = sibling;

      const parts = filename.split(".");
      if (parts.length !== 3 || (parts[2] !== "ts" && parts[2] !== "tsx") || parts[1] === "gen") {
        continue;
      }

      const groupName = filename.split(".")[0];
      nameToFilenames[groupName] ??= [];
      nameToFilenames[groupName].push(filename);
    }

    for (const [name, filenames] of Object.entries(nameToFilenames)) {
      const content = await generateBarrelContent(filenames);
      const outputFilename = `${name}.gen.ts`;
      await Deno.writeTextFile(outputFilename, content);
      console.log(`Generated barrel file: ${outputFilename}`);
    }
  } catch (err) {
    console.error("An error occurred during execution:", err);
  }
}

await main();
