// Automatically generated by "CODEGEN.ts". Do not edit manually.

import type * as URI_xpui_ts from "./URI.xpui.ts";
export let Types: typeof URI_xpui_ts.Types;
export let from: typeof URI_xpui_ts.from;
export let fromString: typeof URI_xpui_ts.fromString;
export let idToHex: typeof URI_xpui_ts.idToHex;
export let hexToId: typeof URI_xpui_ts.hexToId;
export let urlEncode: typeof URI_xpui_ts.urlEncode;
export let isSameIdentity: typeof URI_xpui_ts.isSameIdentity;
export let is: typeof URI_xpui_ts.is;
export let create: typeof URI_xpui_ts.create;
import("./URI.xpui.ts").then((m) => {
  Types = m.Types;
  from = m.from;
  fromString = m.fromString;
  idToHex = m.idToHex;
  hexToId = m.hexToId;
  urlEncode = m.urlEncode;
  isSameIdentity = m.isSameIdentity;
  is = m.is;
  create = m.create;
});
