import type * as uri from "./uri.xpui.ts";

export type ParsableAsURI = any;

export type IsThisURIType<A extends keyof URITypes> = (url: ParsableAsURI) => url is URIClass<A>;

export type URIClass<_A extends keyof URITypes> = any;

export type URITypes = {
  AD: "ad";
  ALBUM: "album";
  APPLICATION: "application";
  ARTIST: "artist";
  ARTIST_TOPLIST: "artist-toplist";
  ARTIST_CONCERTS: "artist-concerts";
  AUDIO: "audio";
  AUDIO_FILE: "audiofile";
  AUTHOR: "author";
  B2B_PARTY: "b2b-party";
  CACHED_FILES: "cached-files";
  CANVAS: "canvas";
  CHAT: "chat";
  CHAT_MESSAGE: "chat-message";
  CLIP: "clip";
  CLIP_VIDEO_CHAPTER: "clip-video-chapter";
  COLLECTION: "collection";
  COLLECTION_ALBUM: "collection-album";
  COLLECTION_ARTIST: "collection-artist";
  COLLECTION_MISSING_ALBUM: "collection-missing-album";
  COLLECTION_TRACK_LIST: "collectiontracklist";
  COMMENT: "comment";
  CONCEPT: "concept";
  CONCERT: "concert";
  CONCERT_GALLERY: "concert-gallery";
  CONCERTS: "concerts";
  CONCERTS_GENRE: "concerts-genre";
  CONCERTS_LOCATION: "concerts-location";
  CONCERTS_LOCATION_GENRE: "concerts-location-genre";
  CONTAINER: "container";
  CONTEXT_GROUP: "context-group";
  CONTRIBUTION: "contribution";
  CONTRIBUTOR: "contributor";
  COURSE: "course";
  CULTURAL_MOMENT: "cultural-moment";
  DAILY_MIX: "dailymix";
  EMPTY: "empty";
  EPISODE: "episode";
  EXPRESSION: "expression";
  FACEBOOK: "facebook";
  FESTIVAL: "festival";
  FOLDER: "folder";
  FOLLOWERS: "followers";
  FOLLOWING: "following";
  GENRE: "genre";
  IMAGE: "image";
  INBOX: "inbox";
  INTERRUPTION: "interruption";
  JAM: "jam";
  KALLAX: "kallax";
  LESSON: "lesson";
  LIBRARY: "library";
  LIST: "list";
  LISTENING_ACTIVITY: "listening-activity";
  LIVE: "live";
  LOCAL_ALBUM: "local-album";
  LOCAL_ARTIST: "local-artist";
  LOCAL: "local";
  LOCAL_TRACK: "local";
  MEDIA: "media";
  MERCHHUB: "merchhub";
  MERCH: "merch";
  MOSAIC: "mosaic";
  PLAYLIST: "playlist";
  PLAYLIST_V2: "playlist-v2";
  PODCAST_CHAPTER: "podcast-chapter";
  POLL: "poll";
  PRERELEASE: "prerelease";
  PRESENTS: "presents";
  PROFILE: "profile";
  PROMOTER: "promoter";
  PROMOTION: "promotion";
  PUBLISHED_ROOTLIST: "published-rootlist";
  QUESTION: "question";
  QUEUE: "queue";
  QUIZ: "quiz";
  RADIO: "radio";
  RESPONSE: "response";
  ROOM: "room";
  ROOTLIST: "rootlist";
  SEARCH: "search";
  SECTION: "section";
  S4A_THIRD_PARTY: "s4a-third-party";
  SHOW: "show";
  SITE: "site";
  SOCIAL_SESSION: "socialsession";
  SPECIAL: "special";
  STARRED: "starred";
  STATION: "station";
  SUPPLEMENTARY_MATERIAL: "supplementarymaterial";
  TEMP_PLAYLIST: "temp-playlist";
  TOPLIST: "toplist";
  TOUR: "tour";
  TRACK: "track";
  TRACKSET: "trackset";
  UNKNOWN: "unknown";
  USER_HIGHLIGHT: "user-highlight";
  USER_TOPLIST: "user-toplist";
  USER_TOP_TRACKS: "user-top-tracks";
  VENUE: "venue";
  VIDEO: "video";
  WRAPPED_PARTY: "wrapped-party";
};

export const URI = {} as typeof uri;

import("./uri.xpui.ts").then((m) => {
  Object.assign(URI, m);
});
