// Automatically generated by "CODEGEN.ts". Do not edit manually.

import type * as React_xpui_ts from "./React.xpui.ts";
export let React: typeof React_xpui_ts.React;
export let ReactJSX: typeof React_xpui_ts.ReactJSX;
export let jsx: typeof React_xpui_ts.jsx;
export let jsxs: typeof React_xpui_ts.jsxs;
export let Fragment: typeof React_xpui_ts.Fragment;
export let ReactDOM: typeof React_xpui_ts.ReactDOM;
export let ReactDOMServer: typeof React_xpui_ts.ReactDOMServer;
import("./React.xpui.ts").then((m) => {
  React = m.React;
  ReactJSX = m.ReactJSX;
  jsx = m.jsx;
  jsxs = m.jsxs;
  Fragment = m.Fragment;
  ReactDOM = m.ReactDOM;
  ReactDOMServer = m.ReactDOMServer;
});
