name: Code Quality
on:
  pull_request:
    branches: ["**"]
  push:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
      - uses: denoland/setup-deno@v2
      - parallel:
          - name: Check formatting
            run: deno run -A npm:oxfmt --check
          - name: Lint
            run: deno run -A npm:oxlint --deny-warnings

  analyze:
    name: Analyze (${{ matrix.language }})
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - language: actions
          - language: javascript-typescript

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: ${{ matrix.language }}
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
        with:
          category: "/language:${{matrix.language}}"
